# Generated by Django 5.0.6 on 2024-06-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='street_address',
            new_name='city',
        ),
    ]
