# Generated by Django 5.0.6 on 2024-06-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_actor_customer_movie_rental_transaction_movie_rental_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_name',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='movie_type',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default=260),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='lusaka', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='street_address',
            field=models.CharField(default='lusaka', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.IntegerField(default=123345),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
