# Generated by Django 5.0.6 on 2024-06-13 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='type',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.genre'),
            preserve_default=False,
        ),
    ]
