# Generated by Django 5.0.6 on 2024-06-09 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customer_city_customer_email_movie_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='street_address',
        ),
    ]
