# Generated by Django 5.0.6 on 2024-06-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_movie_language_delete_movie_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='street_address',
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='email', max_length=50),
        ),
    ]
